// <auto-generated />
using System;
using ManageFileBE.Config;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManageFileBE.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
<<<<<<<< HEAD:BE/ManageFileBE/ManageFileBE/Migrations/20231005083226_InitialCreate.Designer.cs
    [Migration("20231005083226_InitialCreate")]
========
    [Migration("20231005070140_InitialCreate")]
>>>>>>>> dfe0722ed57857e90703b368c4b58c50fd15a953:BE/ManageFileBE/ManageFileBE/Migrations/20231005070140_InitialCreate.Designer.cs
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ManageFileBE.Models.FileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("FileEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
